---
- name: get facts
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - f5networks.f5_modules
  #vars:
 #   provider:
  #    server: "{{ ansible_host }}"
  #    validate_certs: False

  tasks:
    - name: getting facts
      f5networks.f5_modules.bigiq_device_info:
        provider: 
          server: "{{ ansible_host}}"
          validate_certs: False
          server_port: 8443
          user: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
        gather_subset:
          - all
