---
- name: get facts
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - f5networks.f5_modules
  vars:
    provider:
      server: "{{ inventory_hostname }}"
      validate_certs: False

  tasks:
    - name: getting facts
      f5networks.f5_modules.bigiq_device_info:
        provider: "{{ provider }}"
        gather_subset:
          - all
