---
- name: get facts
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - f5networks.f5_modules
  vars:
   provider:
     server: "{{ ansible_host }}"
     validate_certs: False

  tasks:
    - name: getting facts
      f5networks.f5_modules.bigip_device_info:
        provider: "{{ provider }}"
        gather_subset:
          - system-info

    - name: backup ucs
      f5networks.f5_modules.bigip_ucs_fetch:
        src: cs_backup.ucs
        dest: /ucs/backups/cs_backup.ucs
